### ISSUE TITLE
Checkout não apresenta as opções de pagamento na caixa de seleção. 

### ISSUE THREAD

**Issue by awakebrasil** [shipay-pag/shipay-magento-pix-qr-gateway#3]
Boa tarde, 

Fiz a instalação do módulo através da Magento Marketplace, as opções no admin tudo funciona perfeitamente mas no checkout no momento de selecionar a carteira ativa no módulo fica em branco o campo de seleção e recebo a seguinte mensagem de erro no log. 

Não foi possível gerar o token na API Shipay.

Caminho 
vendor/shipay_pagamentos_digitais/shipay-magento-pix-qr-gateway/Gateway/Http/TokenGenerator.php:152

Teriam alguma solução para o erro acima? 

Obrigado.

**Comment by LuizSantos22** [comment]
@awakebrasil Estou com o mesmo problema, vocês conseguiram resolver? Se sim, se importaria de compartilhar a solução conosco?

**Comment by awakebrasil** [comment]
Olá @LuizSantos22 o IP estava bloqueado nos servidores deles, enviei o IP e assim que liberou funcionou ok.

**Comment by LuizSantos22** [comment]
@awakebrasil Desculpe a demora, estive em outros projetos e não vi sua resposta. Onde pego o IP pra enviar pra eles, com o gestor de hosting?

Desde já, obrigado!
